networks:
  app-tier:
    driver: bridge

services:
  mongo:
    image: mongo
    container_name: mongo
    networks:
      - app-tier
    ports:
      - 27017:27017

  pyspark:
    image: jupyter/pyspark-notebook
    container_name: pyspark
    networks:
      - app-tier
    ports:
      - 11000:8888
    volumes:
      - .\exemplos:/home/jovyan/

#   mongo-config3:
#     image: mongo
#     container_name: config3
#     networks:
#       - mongoLojas
#     command: ['mongod', '--configsvr', '--replSet', 'config-server', '--port', '27017']

#   mongo-shard1a:
#     image: mongo
#     container_name: shard1a
#     networks:
#       - mongoLojas
#     command: ['mongod', '--shardsvr', '--replSet', 'shard1', '--port', '27018']

#   mongo-shard1b:
#     image: mongo
#     container_name: shard1b
#     networks:
#       - mongoLojas
#     command: ['mongod', '--shardsvr', '--replSet', 'shard1', '--port', '27018']

#   mongo-shard1c:
#     image: mongo
#     container_name: shard1c
#     networks:
#       - mongoLojas
#     command: ['mongod', '--shardsvr', '--replSet', 'shard1', '--port', '27018']

#   mongo-shard2a:
#     image: mongo
#     container_name: shard2a
#     networks:
#       - mongoLojas
#     command: ['mongod', '--shardsvr', '--replSet', 'shard2', '--port', '27019']

#   mongo-shard2b:
#     image: mongo
#     container_name: shard2b
#     networks:
#       - mongoLojas
#     command: ['mongod', '--shardsvr', '--replSet', 'shard2', '--port', '27019']

#   mongo-shard2c:
#     image: mongo
#     container_name: shard2c
#     networks:
#       - mongoLojas
#     command: ['mongod', '--shardsvr', '--replSet', 'shard2', '--port', '27019']

#   mongo-shard3a:
#     image: mongo
#     container_name: shard3a
#     networks:
#       - mongoLojas
#     command: ['mongod', '--shardsvr', '--replSet', 'shard3', '--port', '27020']

#   mongo-shard3b:
#     image: mongo
#     container_name: shard3b
#     networks:
#       - mongoLojas
#     command: ['mongod', '--shardsvr', '--replSet', 'shard3', '--port', '27020']

#   mongo-shard3c:
#     image: mongo
#     container_name: shard3c
#     networks:
#       - mongoLojas
#     command: ['mongod', '--shardsvr', '--replSet', 'shard3', '--port', '27020']

#   mongo-router1:
#     image: mongo
#     container_name: router1
#     networks:
#       - mongoLojas
#     ports:
#       - 27017:27017
#     depends_on:
#       - config-srv-setup
#       - shard1-setup
#       - shard2-setup
#       - shard3-setup
#     command: ['mongos', '--port', '27017', '--configdb', 'config-server/config1:27017,config2:27017,config3:27017', '--bind_ip_all']

#   config-srv-setup:
#     image: mongo
#     container_name: config-srv-setup
#     volumes:
#       - .\scripts:/scripts
#     depends_on:
#       - mongo-config1
#       - mongo-config2
#       - mongo-config3
#     networks:
#       - mongoLojas
#     restart: no
#     entrypoint: ['bash', './scripts/start-configdb.sh']

#   shard1-setup:
#     image: mongo
#     container_name: shard1-setup
#     volumes:
#       - .\scripts:/scripts
#     depends_on:
#       - mongo-shard1a
#       - mongo-shard1b
#       - mongo-shard1c
#     networks:
#       - mongoLojas
#     restart: no
#     entrypoint: ['bash', './scripts/start-shard1.sh']

#   shard2-setup:
#     image: mongo
#     container_name: shard2-setup
#     volumes:
#       - .\scripts:/scripts
#     depends_on:
#       - mongo-shard2a
#       - mongo-shard2b
#       - mongo-shard2c
#     networks:
#       - mongoLojas
#     restart: no
#     entrypoint: ['bash', './scripts/start-shard2.sh']

#   shard3-setup:
#     image: mongo
#     container_name: shard3-setup
#     volumes:
#       - .\scripts:/scripts
#     depends_on:
#       - mongo-shard3a
#       - mongo-shard3b
#       - mongo-shard3c
#     networks:
#       - mongoLojas
#     restart: no
#     entrypoint: ['bash', './scripts/start-shard3.sh']

#   router-setup:
#     image: mongo
#     container_name: router-setup
#     volumes:
#       - .\scripts:/scripts
#     depends_on:
#       - mongo-router1
#     networks:
#       - mongoLojas
#     restart: no
#     entrypoint: ['bash', './scripts/start-router.sh']
