networks:
  app-tier:
    driver: bridge

services:
  mongo:
    image: mongo
    container_name: mongo
    networks:
      - app-tier
    ports:
      - 27017:27017
    volumes:
      - ./data:/data

  pyspark:
    image: jupyter/pyspark-notebook
    container_name: pyspark
    networks:
      - app-tier
    ports:
      - 11000:8888
    volumes:
      - ./exemplos:/home/jovyan/
